# Deployment do App

apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-temp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app-temp
  template:
    metadata:
      labels:
        app: app-temp
    spec:
      containers:
        - name: app-temp
          image: renanbottero/conversao-temperatura:v1
          ports:
            - containerPort: 8080


---


# Service do App

apiVersion: v1
kind: Service
metadata:
  name: app-temp
spec:
  selector:
    app: app-temp
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30000
  type: LoadBalancer